# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Siyu Bian
title: Ph.D. candidate @ UIUC
email: bsyben@gmail.com
website: https://bsyben.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  bsyben
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: siyu-bian-31577823
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/1600656420340.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Siyu Bian and I'm a Ph.D. candidate at the Department of Agricultural and Consumer Economics in University of Illinois at Urbana-Champaign. I am currently on job market.
  
  I am specialized in risk analysis at agricultural commodity markets. My primary research focus on market microstructure theory, volatility forecasting, options pricing theory, and risk management. 

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: New evidence on market response to public announcements in the presence of microstructure noise
        link: https://www.sciencedirect.com/science/article/pii/S0377221721006251
        # link_text: Project Website
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          with Teresa Serra, Philip Garcia, and Scott H. Irwin
        description: | # this will include new lines to allow paragraphs
          Market responses to public news announcements are commonly measured by their impact on price returns variance, which allows inference on the value of information and the length of the price discovery process. Recently published articles based on high-frequency data fail to disentangle efficient market price variance from microstructure noise, which produces biased estimates of announcements’ market impacts. By using a Markov Chain framework, we address the shortcomings of previous research and assess the market response to key public information releases affecting agricultural markets. We compare two mechanisms to release public information that have been used in these markets: the trading halt and the real-time. We show how the value of microstructure noise can be used to improve public policy decisions. We find that the real-time release of information brings faster efficient price discovery at the cost of large microstructure frictions. Increases in the cost of noise are not compensated by the improvements in the speed of efficient price discovery. Overall, our findings are highly relevant to public policy and have implications for market design.
  
  - title: Working Papers
    layout: list
    content:
      - layout: top-middle
        title: Is nonlinearity necessary for realized volatility forecasting (Job Market Paper)
        quote: >
          with Anabelle Couleau, Teresa Serra, and Philip Garcia
        description:
         Our findings show that the linear models outperform nonlinear machine learning algorithms in out-of-sample volatility forecasting. We then design a hybrid neural network that chooses between linear and nonlinear structures when forecasting volatility. The hybrid neural network decomposes its forecasts into linear and nonlinear components. The decomposition results suggest that nonlinear components amount to between 0% to 25% of total volatility.
          
      - layout: top-middle
        title: Intraday Volatility Pattern in Lean Hog and Corn Futures Market During PEDV Outbreak
        description:
          In 2014 hog and corn market prices reflected the consequences of the Porcine Epidemic Diarrhea Virus (PEDV) outbreak. This research studies, for the first time, the impact of the PEDV outbreak on the daily covariance of lean hog and corn intraday futures price returns. My results suggest that the PEDV crisis caused relevant increases in the lean hog (increase by 250%) and corn (increase by 150%) price return variances, and much stronger changes in the spillovers between the two markets (increase between 400% to 500%). Results also suggest that, due to substantial increases (about 600%) in market microstructure noise after the PEDV outbreak, observed return covariances constitute a relevant biased estimation of efficient return covariances.

          
  
  - title: Internship Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: McKinsey & Company
        link: https://www.mckinsey.com/
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: May 2019 - Aug 2019
        description: | # this will include new lines to allow paragraphs
          - Helped a major steel production corporation refine raw material procurement process
          - Created price forecast models with machine learning techniques for edible oil prices based on yield forecast
          - Evaluated the potential forecast capabilities for both price and production levels of pork by-products in China for a pharmaceutical company

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Illinois at Urbana-Champaign
        caption: 2015 - Current
        sub_title: Ph.D. in Applied Economics
        
      - layout: top-middle
        title: University of Wisconsin - Madison
        caption: 2013 - 2015
        sub_title: Master in Economics
        
      - layout: top-middle
        title: University of Iowa
        caption: 2009 - 2013
        sub_title: B.B.A. in Economics and Finance, Minors in Math and Statistics
  
  - title: Skills
    layout: text
    content:
      R, Python, SQL, LATEX, Git

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
